#!/usr/bin/env bash
# displays numbers from 1 to 100:
# - Displays FizzBuzz when the number is a multiple  3 and 5
# - Displays Fizz when the number is multiple  3
# - Displays Buzz when the number is a multiple  5
# - Otherwise, displays the number
for num in {1..100}; do
    if [ $((num % 5)) -eq 0 ] && [ $((num % 3)) -eq 0 ]; then
	echo "FizzBuzz"
    elif [ $((num % 5)) -eq 0 ]; then
	echo "Buzz"
    elif [ $((num % 3)) -eq 0 ]; then
	echo "Fizz"
    else
	echo "$num"
    fi
done
